### ISSUE TITLE
kusanagi-nginx:1.17.1-r0 dies as "can't open default.conf.template: no such file"

### ISSUE THREAD

**Issue by PicoSushi** [prime-strategy/kusanagi-nginx#2]
[公式のdocker-compose.yml](https://kusanagi.tokyo/cloud/kusanagi-runs-on-docker/)を利用し、 `kusanagi-nginx:1.17.1-r0` で起動すると以下のようにエラーを吐いて終了します。

```
kusanagi-nginx      | /docker-entrypoint.sh: line 33: can't open default.conf.template: no such file
kusanagi-nginx exited with code 1
```

# 実際に使用した docker-compose.yml
```
# cat docker-compose.yml
version: '2'

services:
  kusanagi-data:
    container_name: kusanagi-data
    image: busybox
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /var/lib/mysql
      - /etc/nginx/conf.d
      - /etc/httpd/conf.d
      - /etc/kusanagi.d
      - /home/kusanagi
    command: /bin/sh

  kusanagi-nginx:
    container_name: kusanagi-nginx
    image: primestrategy/kusanagi-nginx:1.17.0-r1
    environment:
      PROFILE: kusanagi
      FQDN: kusanagi.example.jp
      WPLANG: ja
      BCACHE: "off"
      FCACHE: "off"
    volumes_from:
      - kusanagi-data
    links:
      - kusanagi-php7:php
      - kusanagi-mariadb:mysql
    ports:
      - "80:80"
      - "443:443"

  kusanagi-mariadb:
    container_name: kusanagi-mariadb
    image: mariadb:10.0.24
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER:     user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes_from:
      - kusanagi-data

  kusanagi-php7:
    container_name: kusanagi-php7
    image: primestrategy/kusanagi-php7:7.0.6-1
    links:
      - kusanagi-mariadb:mysql
    volumes_from:
      - kusanagi-data
```

**Comment by firstval** [comment]
same here still not resolve at 1.17.5-r0

**Comment by s-miyaza** [comment]
ja:
バグレポートありがとうございます。
kusanagi-docker やその他バージョンが古いようです。
現在、1.0.3がリリースされているのでそちらをお使い下さい。
kusanagi-docker を再インストールするのが一番早いと思います。
primestrategy/nginx-1.17.5-r0 でも同じ現象が起きているとのことですが、こちらで以下のコマンドを試したところ特に問題ありませんでした。
```
docker -v
Docker version 19.03.4, build 9013bf583a
docker run -it primestrategy/kusanagi-nginx:1.17.5-r0 sh
```
docker 18.06以降では問題ないはずです。このコマンドを実行して問題あるようだと、
使用OSか、dockerもしくはdocker-composeのバージョン問題かもしれません。
発生したOSとバージョン、docker と docker-composeを教えてください。

en:
Thank you for the bug report.
It seems that kusanagi-docker and other versions are out of date.
Please use 1.0.3 now because it is released.
I think it's the quickest way to reinstall kusanagi-docker.
primestrategy/nginx-1.17.5-r0  also said the same behavior is occurring, but there was no problem when I tried the following command here.
```
docker -v
Docker version 19.03.4, build 9013bf583a
docker run -it primestrategy/kusanagi-nginx:1.17.5-r0 sh
```
It should not be a problem with docker 18.06 and later.
If you run this command and there seems to be a problem, it may be a version problem with docker or docker-compose. Please check the version of docker.
What OS and version did you encounter, docker and docker-compose?

**Comment by firstval** [comment]
this is the format of my docker-compose

```
version: '2'

services:
  kusanagi-data:
    container_name: kusanagi-data
    image: busybox
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /var/lib/mysql
      - /etc/nginx/conf.d
      - /etc/httpd/conf.d
      - /etc/kusanagi.d
      - /home/kusanagi
    command: /bin/sh

  kusanagi-nginx:
    container_name: kusanagi-nginx
    image: primestrategy/kusanagi-nginx:1.17.5-r0
    environment:
      PROFILE: kusanagi
      FQDN: kusanagi.example.jp
      WPLANG: ja
      BCACHE: "off"
      FCACHE: "off"
    volumes_from:
      - kusanagi-data
    links:
      - kusanagi-php7:php
      - kusanagi-mariadb:mysql
    ports:
      - "80:80"
      - "443:443"

  kusanagi-mariadb:
    container_name: kusanagi-mariadb
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER:     user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes_from:
      - kusanagi-data

  kusanagi-php7:
    container_name: kusanagi-php7
    image: primestrategy/kusanagi-php7:7.3.5-r0
    links:
      - kusanagi-mariadb:mysql
    volumes_from:
      - kusanagi-data
```

still getting same error with 

```
$ docker -v
Docker version 19.03.5, build 633a0ea
$ docker-compose -v
docker-compose version 1.24.1, build 4667896b
```
